language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.0
      env: UUID_VERSION='~2.0'
    - php: 7.0
      env: UUID_VERSION='~3.0'

before_install:
  - if [ "$UUID_VERSION" != "" ]; then composer require --dev --no-update ramsey/uuid=$UUID_VERSION; fi

install:
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit --exclude-group=none
